# Generated by Django 4.0.5 on 2022-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grades', models.CharField(max_length=100)),
                ('average_grade', models.FloatField()),
            ],
        ),
    ]
